services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.local.conf:/etc/nginx/nginx.conf
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /d–∞ta/redis:/root/redis
    environment:
      - REDIS_PORT=6379
  db:
    image: postgres
    container_name: sorting_visualizer_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sorting_visualizer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5430" # Publishes 5430 to other containers but NOT to host machine
    ports:
      - "5430:5430"
    command: -p 5430
  web:
    build: .
    container_name: sorting_visualizer_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=sorting_visualizer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
