services:
#  nginx:
#    image: nginx:1.25.4
#    container_name: visualizer_nginx
#    ports:
#      - 8000:80
#    volumes:
#      - ./config/nginx/nginx.local.conf:/etc/nginx/nginx.conf
#      - ./static:/code/static
#    depends_on:
#      - server
  redis:
    image: redis:7.2.4
    container_name: visualizer_redis
    restart: always
    ports:
      - "6579:6579"
    volumes:
      - /d–∞ta/redis:/root/redis
    command: --port 6579
    environment:
      - REDIS_PORT=6579
  db:
    image: postgres:15.6
    container_name: visualizer_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sorting_visualizer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5430" # Publishes 5430 to other containers but NOT to host machine
    ports:
      - "5430:5430"
    command: -p 5430
  server:
    build: .
    container_name: visualizer_server
    command: python manage.py runserver 0.0.0.0:8000
#    expose:
#      - 8001
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
#  gunicorn:
#    build: .
#    container_name: visualizer_gunicorn
#    command: gunicorn visualizer.wsgi:application --name visualizer_app --workers 1 --bind=0.0.0.0:8000 --log-level=debug --reload --reload-engine=poll --reload-extra-file=/code/apps/chat/templates/chat/index.html
#    expose:
#      - 8000
#    volumes:
#      - .:/code
#    #ports:
#    #  - "8000:8000"
#    environment:
#      - POSTGRES_NAME=sorting_visualizer
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db
#volumes:
#  code:
