FROM python:3.12-alpine
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE="config.settings.dev"

RUN apk update \
        && apk add --no-cache bash \
        && pip install pipenv

WORKDIR /app
#COPY Pipfile /app/
#COPY Pipfile.lock /app/
COPY . /app/

RUN addgroup -S spacer
RUN adduser --shell /bin/bash -h /home/spacer -D -G spacer spacer

RUN chown -R spacer:spacer /app
RUN pipenv install --dev --system --deploy

USER spacer
