FROM python:3.12-alpine
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE="config.settings.dev"

RUN apk update \
        && apk add --no-cache git openssh-client bash \
        && pip install pipenv

WORKDIR /app
COPY Pipfile /app/
COPY Pipfile.lock /app/
RUN pipenv install --dev --system --deploy
COPY . /app/
