services:
  nginx:
    image: nginx:latest
    container_name: visualizer_nginx
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/nginx.local.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  redis:
    image: redis:latest
    container_name: visualizer_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /d–∞ta/redis:/root/redis
    environment:
      - REDIS_PORT=6379
  db:
    image: postgres
    container_name: visualizer_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sorting_visualizer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5430" # Publishes 5430 to other containers but NOT to host machine
    ports:
      - "5430:5430"
    command: -p 5430
  web:
    build: .
    container_name: visualizer_web
    command: gunicorn visualizer.wsgi:application --name visualizer_app --workers 1 --bind=unix:/code/run/gunicorn.sock --log-level=debug --reload --log-file=-
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=sorting_visualizer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
