services:
  redis:
    image: redis:7.2.4
    container_name: visualizer_redis
    restart: always
    ports:
      - "6579:6579"
    volumes:
      - /d–∞ta/redis:/root/redis
    command: --port 6579
    environment:
      - REDIS_PORT=6579
  db:
    image: postgres:15.6
    container_name: visualizer_db
    user: 1000:1000
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sorting_visualizer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5430" # Publishes 5430 to other containers but NOT to host machine
    ports:
      - "5430:5430"
    command: -p 5430
  server:
    build:
      dockerfile: Dockerfile-dev
    container_name: visualizer_server
    command: python manage.py runserver 0.0.0.0:9000
#    expose:
#      - 8001
    ports:
      - "9000:9000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
#volumes:
#  code:
