#!/bin/bash

NAME="sorting_visualizer_gunicorn_workers"               # Name of the application
DJANGODIR=/app                   # Django project directory
SOCKFILE=/app/run/gunicorn.sock  # we will communicte using this unix socket
USER=spacer                                          # the user to run as
GROUP=spacer                                        # the group to run as
NUM_WORKERS=2                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=config.settings.prod             # which settings file should Django use
DJANGO_WSGI_MODULE=visualizer.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec `/home/spacer/.local/bin/pipenv --venv`/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=error \
  --reload \
  --log-file=-
