#!/bin/bash

NAME="sorting_visualizer_daphne_server"            # Name of the application
DJANGODIR=/var/www/sorting-visualizer
USER=spacer                                        # the user to run as
GROUP=spacer                                        # the group to run as
NUM_WORKERS=2                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=config.settings.prod         # which settings file should Django use
DJANGO_ASGI_MODULE=visualizer.asgi

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec `/home/spacer/.local/bin/pipenv --venv`/bin/daphne ${DJANGO_ASGI_MODULE}:application \
  --unix-socket=/var/www/sorting-visualizer/run/daphne.sock \
  --websocket_timeout=86400 \
  --websocket_connect_timeout=86400 \
  --server-name=$NAME \
  --verbosity=3
