#!/bin/bash

NAME="sorting_visualizer_daphne_server"            # Name of the application
USER=spacer                                        # the user to run as
GROUP=spacer                                        # the group to run as
NUM_WORKERS=2                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=config.settings.prod         # which settings file should Django use

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec /home/spacer/.local/bin/pipenv run daphne \
  -e ssl:8001:privateKey=/var/www/sorting-visualizer/privkey.pem:certKey=/var/www/sorting-visualizer/cert.pem \
  --log-level=debug \
  visualizer.asgi:application
